title: Voxelmanip Luanti Wiki
description: The Voxelmanip Luanti Wiki...

repo: https://github.com/rollerozxa/voxelmanip-wiki

exclude:
  - README.md

sass:
  style: compressed
  sourcemap: never

collections:
  redirects:
    permalink: /:path
    output: true

defaults:
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      path: ""
      type: "redirects"
    values:
      layout: "redirect"
