<?php

$pageRedirects = [
    'Compiling_on_Windows_using_MSYS2' => 'https://dev.luanti.org/compiling-on-windows-using-msys2/',
    'Custom_Fonts' => '',
    'Custom_Lua_Mapgen' => 'https://dev.luanti.org/custom-lua-mapgen/',
    'Development_Tools' => 'https://dev.luanti.org/development-tools/',
    'Distributing_Minetest_Games' => 'https://dev.luanti.org/distributing-luanti-games/',
    'Documentation_Resources' => 'https://dev.luanti.org/modding-intro/',
    'Filesystem' => 'https://dev.luanti.org/docs/filesystem/',
    'Game_Namespaces' => '',
    'Game_Theme_Reimplementation' => 'https://dev.luanti.org/game-theme-reimplementation/',
    'Improving_Build_Times' => 'https://dev.luanti.org/improving-build-times/',
    'ItemStackMetaData' => 'https://dev.luanti.org/docs/classes/itemstackmetadata/',
    'Keeping_World_Compatibility' => 'https://dev.luanti.org/keeping-world-compatibility/',
    'Limitations' => 'https://dev.luanti.org/limitations/',
    'LuaJIT' => 'https://dev.luanti.org/luajit/',
    'LuaJIT_Differences' => 'https://dev.luanti.org/luajit-differences/',
    'Lua_Environment' => 'https://dev.luanti.org/docs/lua-environment/',
    'Mapgen_Optimisations' => 'https://dev.luanti.org/mapgen-memory-optimisations/',
    'MetaData' => 'https://dev.luanti.org/docs/classes/metadata/',
    'Minetest_NMPR' => 'https://dev.luanti.org/engine/nmpr/',
    'ModStorage' => 'https://dev.luanti.org/docs/classes/modstorage/',
    'Mod_Dependency_Management' => 'https://dev.luanti.org/mod-dependency-management/',
    'Modchannels' => 'https://dev.luanti.org/docs/modchannels/',
    'NodeMetaData' => 'https://dev.luanti.org/docs/classes/nodemetadata/',
    'Nodes' => '',
    'Object_Properties' => 'https://dev.luanti.org/docs/object-properties/',
    'Persistence' => 'https://dev.luanti.org/docs/persistence/',
    'PlayerMetaData' => 'https://dev.luanti.org/docs/classes/playermetadata/',
    'Random' => 'https://dev.luanti.org/docs/classes/random/',
    'Raycast' => 'https://dev.luanti.org/docs/classes/raycast/',
    'Remote_Media' => 'https://dev.luanti.org/remote-media/',
    'Right_to_a_Name' => '',
    'Schematics' => 'https://dev.luanti.org/schematic/',
    'Setting_up_a_server' => 'https://dev.luanti.org/setting-up-a-server/',
    'Spawn_Algorithm' => 'https://dev.luanti.org/spawn-algorithm/',
    'Texture_Modifiers' => 'https://dev.luanti.org/docs/texture-modifiers/',
    'Textures' => 'https://dev.luanti.org/textures/',
    'Timing_and_Event_loop' => 'https://dev.luanti.org/docs/timing-and-event-loop/',
    'Using_Blockbench' => 'https://dev.luanti.org/using-blockbench/',
    'Vector_API' => 'https://dev.luanti.org/docs/classes/vector/',
    'VoxelArea' => 'https://dev.luanti.org/docs/classes/voxelarea/',
];

